---
output: 
  html_document:
    keep_md: TRUE
---

# When is it used?

&nbsp;

Odds ratios are most commonly used in __case-control studies__ to compare the relative odds of the occurrence of the outcome of interest (e.g. disease or disorder), given exposure to the variable of interest (e.g. health characteristic, aspect of medical history). Ruby’s example is a simple case-control study!

* OR=1 Exposure does not affect odds of outcome
* OR>1 Exposure associated with higher odds of outcome
* OR<1 Exposure associated with lower odds of outcome

They can also be used in __cross-sectional__ and __cohort study__ designs as well to determine whether a particular exposure is a risk factor for a particular outcome, and to compare the magnitude of various risk factors for that outcome (with some modifications and/or assumptions).

### Example (Cohort study):

In an article published in the Journal in November 2008, Greenfield and colleagues looked at previously suicidal adolescents (n=263) to analyze the associations between presence of psychiatric disorderand suicidal behavior at six-month follow-up (Greenfield et al., 2008). In the study, 186 of the 263 adolescents did not exhibit suicidal behaviour (non-suicidal, NS) at six months follow-up. Of this group, 86 young people (86/186) had been assessed as having depression at baseline. Of the 77 young people with persistent suicidal behavior at follow-up (suicidal behaviour, SB), 45 had been assessed as having depression at baseline (45/77).

